version: '3.9'

services:
  # monolite:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./monolit-back-end
  #   image: monolit:improved
  #   container_name: monolit-container
  #   restart: always
  #   networks:
  #     - servers
  #   ports:
  #     - "44333:44333"
  #   depends_on:
  #     - database
  ms-tours:
    build:
      dockerfile: Dockerfile
      context: ./ms-back-end/ms-tours
    image: microservice-tours:improve7
    container_name: ms-tours-container
    restart: always
    networks:
      - servers
    ports:
      - "8081:8081"
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: ms-tours
      PGSEARCHPATH: tours
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-data:
    name: ms-tours-database-data

networks:
  servers:
    name: servers
    driver: bridge