version: '3.9'

services:

  ms-tours:
    build:
      dockerfile: Dockerfile
      context: ./ms-back-end/ms-tours
    image: microservice-tours:improve7
    container_name: ms-tours-container
    restart: always
    networks:
      - servers
    ports:
      - "8081:8081"
    depends_on:
      - ms-tours-database

  ms-blogs:
    build:
      dockerfile: Dockerfile
      context: ./ms-back-end/ms-blogs
    image: microservice-blogs:improve7
    container_name: ms-blogs-container
    restart: always
    networks:
      - servers
    ports:
      - "8080:8080"
    depends_on:
      - ms-blogs-database

  ms-tours-database:
    image: postgres:13
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: ms-tours
      PGSEARCHPATH: tours
    volumes:
      - ms-tours-database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ms-blogs-database:
    image: postgres:13
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: ms-blogs
      PGSEARCHPATH: blogs
    volumes:
      - ms-blogs-database-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  ms-tours-database-data:
    name: ms-tours-database-data

  ms-blogs-database-data:
    name: ms-blogs-database-data

networks:
  servers:
    name: servers
    driver: bridge
