version: "3.8"

services:

  stakeholders-service:
    image: stakeholders-service
    container_name: stakeholders-service
    hostname: stakeholders-service
    build:
      context: ./ms-stakeholders/
      dockerfile: Dockerfile
    restart: always
    environment:
      STAKEHOLDER_SERVICE_ADDRESS: ${STAKEHOLDER_SERVICE_ADDRESS}
    networks:
      - network
    depends_on:
      - ms-stakeholders-database

  ms-stakeholders-database:
    image: postgres:13
    restart: always
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: ms-stakeholders
      PGSEARCHPATH: stakeholders
    volumes:
      - ms-stakeholders-database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_gateway1:
    image: api_gateway1
    container_name: api_gateway1
    hostname: api_gateway1
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment:
      STAKEHOLDER_SERVICE_ADDRESS: stakeholders-service:8084
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
    depends_on:
      - stakeholders-service
    networks:
      - network
    ports:
      - "8084:8084"

volumes:
  ms-stakeholders-database-data:
    name: ms-stakeholders-database-data

networks:
  network:
    driver: bridge