version: "3.8"

services:

  stakeholders-service:
    image: stakeholders-service
    container_name: stakeholders-service
    hostname: stakeholders-service
    build:
      context: ./ms-stakeholders/
      dockerfile: Dockerfile
    restart: always
    environment:
      STAKEHOLDER_SERVICE_ADDRESS: ${STAKEHOLDER_SERVICE_ADDRESS}
    networks:
      - network

  api_gateway1:
    image: api_gateway1
    container_name: api_gateway1
    hostname: api_gateway1
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment:
      STAKEHOLDER_SERVICE_ADDRESS: stakeholders-service:8084
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
    depends_on:
      - stakeholders-service
    networks:
      - network
    ports:
      - "8084:8084"

networks:
  network:
    driver: bridge