version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "user-server"
    hostname: "user-server"
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=adminadmin
    depends_on:
      neo4j:
        condition: service_healthy

  # NoSQL: Neo4J DB
  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    healthcheck:
      # test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p adminadmin || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/adminadmin
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
